vault_addr: "http://127.0.0.1:8200"

pki_path: "pki"
pki_max_lease_ttl: 87600h
pki_ca:
  type: internal
  common_name: "services.internal"
  ttl: 87600h
pki_roles:
  - name: internal_communication
    settings:
      allowed_domains:
        - vagrant.local
      allow_subdomains: true
      max_ttl: 8640h
pki_policies:
  - name: common
    rules:
      path:
        "pki/sign/internal_communication":
          capabilities:
            - create
            - read
            - update
            - list
pki_tokens:
  - role_name: common
    settings:
      allowed_policies:
        - common
      orphan: true
      renewable: false
      token_explicit_max_ttl: "8640h"

base_dir_output: "{{ playbook_dir | dirname | dirname }}/tokens/vault/{{ inventory_dir | basename }}"

unseal_keys_dir_output: "{{ base_dir_output }}/unseal_keys"
root_token_dir_output: "{{ base_dir_output }}/root_token"
tokens_dir_output: "{{ base_dir_output }}/tokens"

#vault_unseal_key: ""
#vault_root_token: ""