- name: Read token
  command: cat {{ item }}
  register: root_token
  with_fileglob: "{{ root_token_dir_output }}/rootkey"
  delegate_to: localhost
  become: no

- name: Enable pki secret
  shell: |
    vault secrets enable -path {{ pki.path }} pki
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ item.stdout }}"
  with_items: "{{ root_token.results }}"
  register: enable_results
  failed_when: "enable_results.rc == 1"
  changed_when: "enable_results.rc == 0"

- name: Tune pki path
  shell: |
    vault secrets tune -max-lease-ttl={{ pki.max_lease_ttl }} {{ pki.path }}
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ item.stdout }}"
  with_items: "{{ root_token.results }}"

- name: Generate internal CA
  shell: |
    vault write {{ pki.path }}/root/generate/internal common_name={{ pki.ca_common_name }} ttl={{ pki.ca_ttl }}
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ item.stdout }}"
  with_items: "{{ root_token.results }}"
  register: generate_results
  changed_when: "'existing root certificate' in generate_results.stdout"