---
# File: defaults/main.yml - default variables for Vault

# ---------------------------------------------------------------------------
# Core variables
# ---------------------------------------------------------------------------

# Package variables
vault_version: "{{ lookup('env','VAULT_VERSION') | default('1.3.2', true) }}"
vault_architecture_map:
  # this first entry seems... redundant (but it's required for reasons)
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
vault_architecture: "{{ vault_architecture_map[ansible_architecture] }}"
vault_os: "{{ ansible_system|lower }}"
vault_pkg: "vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
vault_shasums: "vault_{{ vault_version }}_SHA256SUMS"

vault_base_url: "https://releases.hashicorp.com/vault"

vault_zip_url: "{{ vault_base_url }}/{{ vault_version }}/vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
vault_checksum_file_url: "{{ vault_base_url }}/{{ vault_version }}/vault_{{ vault_version}}_SHA256SUMS"

# Paths
vault_bin_path: /usr/local/bin
vault_config_path: /etc/vault.d
vault_plugin_path: /usr/local/lib/vault/plugins
vault_data_path: /var/vault
vault_log_path: /var/log/vault
vault_run_path: /var/run/vault
vault_home: "/opt/home/{{ vault_user }}"

# System user and group
vault_manage_user: true
vault_user: vault
vault_manage_group: false
vault_group: bin

# Logging
vault_enable_logrotate: true
vault_logrotate_freq: 7
vault_logrotate_template: vault_logrotate.j2

# ---------------------------------------------------------------------------
# Vault variables
# ---------------------------------------------------------------------------

vault_cluster_name: dc1
vault_log_level: "{{ lookup('env','VAULT_LOG_LEVEL') | default('info', true) }}"
vault_iface: "{{ lookup('env','VAULT_IFACE') | default(ansible_default_ipv4.interface, true) }}"
vault_address: "{{ hostvars[inventory_hostname]['ansible_'+vault_iface]['ipv4']['address'] }}"
vault_ui: "{{ lookup('env', 'VAULT_UI') | default(true, true) }}"
vault_port: 8200
vault_main_config: "{{ vault_config_path }}/vault_main.hcl"
vault_main_configuration_template: vault_main_configuration.hcl.j2

# ---------------------------------------------------------------------------
# Storage backend
# ---------------------------------------------------------------------------

vault_backend: file
vault_backend_file: vault_backend_file.j2

vault_cluster_disable: false
vault_cluster_address: "{{ hostvars[inventory_hostname]['ansible_'+vault_iface]['ipv4']['address'] }}:{{ (vault_port | int) + 1}}"
vault_cluster_addr: "{{ vault_protocol }}://{{ vault_cluster_address }}"
vault_api_addr: "{{ vault_protocol }}://{{ vault_redirect_address | default(hostvars[inventory_hostname]['ansible_'+vault_iface]['ipv4']['address']) }}:{{ vault_port }}"

vault_max_lease_ttl: "768h"
vault_default_lease_ttl: "768h"

# Storage tls settings
vault_backend_tls_src_files: "{{ vault_tls_src_files }}"
vault_backend_tls_config_path: "{{ vault_tls_config_path }}"
vault_backend_tls_cert_file: "{{ vault_tls_cert_file }}"
vault_backend_tls_key_file: "{{ vault_tls_key_file }}"
vault_backend_tls_ca_file: "{{ vault_tls_ca_file }}"

# ---------------------------------------------------------------------------
# Initialization and startup script templates
# ---------------------------------------------------------------------------

vault_systemd_template: vault_service_systemd.j2

# ---------------------------------------------------------------------------
# TLS variables
# ---------------------------------------------------------------------------

# NB: at the end of the role there's a API Reachability check; if you rely on
# self-signed certificates you might need to change the following to false
validate_certs_during_api_reachable_check: true

vault_tls_config_path: "{{ lookup('env','VAULT_TLS_DIR') | default('/etc/vault/tls', true) }}"
vault_tls_src_files: "{{ lookup('env','VAULT_TLS_SRC_FILES') | default(role_path+'/files', true) }}"

vault_tls_disable: "{{ lookup('env','VAULT_TLS_DISABLE') | default(1, true) }}"
vault_tls_gossip: "{{ lookup('env','VAULT_TLS_GOSSIP') | default(0, true) }}"

vault_tls_copy_keys: true
vault_protocol: "{% if vault_tls_disable %}http{% else %}https{% endif %}"
vault_tls_cert_file: "{{ lookup('env','VAULT_TLS_CERT_FILE') | default('vault.crt', true) }}"
vault_tls_key_file: "{{ lookup('env','VAULT_TLS_KEY_FILE') | default('vault.key', true) }}"
vault_tls_ca_file: "{{ lookup('env','VAULT_TLS_CA_CRT') | default('ca.crt', true) }}"

vault_tls_min_version: "{{ lookup('env','VAULT_TLS_MIN_VERSION') | default('tls12', true) }}"
vault_tls_cipher_suites: ""
vault_tls_prefer_server_cipher_suites: "{{ lookup('env','VAULT_TLS_PREFER_SERVER_CIPHER_SUITES') | default('false', true) }}"
vault_tls_files_remote_src: false
vault_tls_require_and_verify_client_cert: false
vault_tls_disable_client_certs: false

# ---------------------------------------------------------------------------
# Seal variables
# ---------------------------------------------------------------------------

# pkcs11 seal
vault_backend_seal: vault_seal_pkcs11.j2
vault_seal_lib: /lib64/hsmlibrary.so
vault_seal_pin: 12345
vault_seal_key_label: vault-hsm-key
vault_seal_generate_key: false
vault_seal_key_mechanism: ''
vault_seal_token_label: ''
vault_seal_slot: 0
vault_softcard_enable: false
vault_telemetry_enabled: false
